version: '3.8'

services:

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter_app
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data_files:/home/jovyan/work
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  metabase:
    image: metabase/metabase:v0.55.x
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ./metabase_data:/metabase-data
      - ./data_files/notebooks/sqlitedb.db:/sqlitedb.db 
    depends_on:
      - db
    restart: unless-stopped

